In [34]:
import numpy as np

In [35]:
# columns: [age, math mark , science mark]
data = np.array([
                [18,85,78],  # student 1
                [19,92,88],  # student 2
                [17,76,95],  # student 3
                [18,65,70],  # student 4
                [20,90,85]   # student 5
                         ])

In [36]:
data.shape

(5, 3)

In [37]:
# find the avarage of age students
np.mean(data[:,0])

np.float64(18.4)

In [38]:
# extract maths mark of the student 
data[:,0]

array([18, 19, 17, 18, 20])

In [39]:
# find the higest science mark
np.max(data[:,2])

np.int64(95)

In [40]:
# get details of the student who scored mored than 90 in maths
data[data[:,1] > 90]

array([[19, 92, 88]])

In [41]:
# increase maths mark all student by 5
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [44]:
# find student who yeanger than 19
len(data[data[:,0] < 19])

3

In [45]:
# calculate the avarage marks in each subject (columns-wise  mean)
np.mean(data[:,1:],axis = 0)

array([86.6, 83.2])

In [46]:
# get data of students who at least scored 80 marks in both subject
data[(data[:,1] >= 80 ) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [48]:
# replace all science marks < 75 with zero
data[:,2][data[:,2] < 75 ] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])