In [3]:
import numpy as np

In [4]:
arr = np.array([12,21,43,41,55,65,37])
arr1 = np.array([77,76,56,84,43,25,14])
sum_arr = arr + arr1
sum_arr

array([ 89,  97,  99, 125,  98,  90,  51])

In [5]:
sub_arr = arr - arr1
sub_arr

array([-65, -55, -13, -43,  12,  40,  23])

In [6]:
multi_arr = arr * arr1
multi_arr

array([ 924, 1596, 2408, 3444, 2365, 1625,  518])

In [7]:
div_arr = arr / arr1
div_arr

array([0.15584416, 0.27631579, 0.76785714, 0.48809524, 1.27906977,
       2.6       , 2.64285714])

In [8]:
floor_arr = arr // arr1
floor_arr

array([0, 0, 0, 0, 1, 2, 2])

In [9]:
expo_arr = arr ** arr1
expo_arr

array([                   0, -3321159092462303983, -1577905608676222815,
        -127992810615553887, -4502227472361539161,  3902757015977641537,
       -8396556048962440535])

In [10]:
a = [10,22,33,44,55,66]
arr = np.array(a)

In [11]:
arr + 10 # broadcasting

array([20, 32, 43, 54, 65, 76])

In [12]:
arr = np.arange(1,21).reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [13]:
sum_arr1 = arr + 10
sum_arr1

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [14]:
arr = np.arange(1,21)
arr  # Deep Copy and Shallow Copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice = arr[:4]
slice = slice * 10
slice

array([10, 20, 30, 40])

In [17]:
arr[3:9] * 20

array([ 80, 100, 120, 140, 160, 180])

In [18]:
a
b = a.copy()

In [20]:
b[0]=99
b

[99, 22, 33, 44, 55, 66]

In [21]:
a

[10, 22, 33, 44, 55, 66]

In [22]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [23]:
arr1

array([[1, 2],
       [3, 4]])

In [24]:
arr2

array([[5, 6],
       [7, 8]])

In [25]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [26]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [27]:
arr1

array([[1, 2],
       [3, 4]])

In [28]:
arr1.T

array([[1, 3],
       [2, 4]])

In [31]:
# Advance Array Manupilation

In [32]:
arr3 = np.array([1,2,3,4])  # Stacking Array
arr4 = np.array([5,6,7,8])

In [33]:
np.vstack((arr3,arr4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
np.hstack((arr3,arr4))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.column_stack((arr3,arr4))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [36]:
c = np.arange(16).reshape(4,4) # Splitting Array
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [41]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [42]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [45]:
n = np.vsplit(c,4)

In [46]:
for i in n:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
