In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [4]:
arr[1::2]

array([12, 14, 16, 18, 20])

In [6]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
arr[5]

array([26, 27, 28, 29, 30])

In [9]:
arr[3]

np.int64(18)

In [10]:
arr[3,4]

np.int64(20)

In [12]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [21]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [22]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [25]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [28]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])