In [8]:
import numpy as np
arr = np.zeros((5,10)) 
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [15]:
arr = np.ones((3,5)) # one print in row and columns , 3 rows and 5 columns
arr


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [37]:
arr = np.linspace(1,5,10) 
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [40]:
arr = np.random.rand(10)
arr

array([0.39424164, 0.08921936, 0.55261129, 0.97722708, 0.04116572,
       0.61261888, 0.74763285, 0.56173794, 0.5059781 , 0.45466156])

In [41]:
arr = np.random.randn(10)
arr

array([ 1.00848676, -0.39107505, -0.58733479, -1.3575191 , -0.93013523,
        0.5053198 ,  1.3030326 , -2.48904241, -0.23504023, -0.8171387 ])

In [43]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) # this is 3 by 3  2D array 
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr.shape   # This is a array attributes

(3, 3)

In [45]:
arr.size

9

In [46]:
arr.dtype

dtype('int64')

In [49]:
arr.min() # this is a array methods 

np.int64(1)

In [50]:
arr.max()

np.int64(9)

In [54]:
arr.sum()

np.int64(45)

In [59]:
np.sum(arr,axis = 0) # this is a add the number columns wise ex 1 + 4 + 7 = 12 ,  all columns  elements sum separate and store one row                          

array([12, 15, 18])

In [60]:
np.sum(arr,axis = 1) # this is add element by row wise ex 1 + 2 + 3 = 6 all rows element sum separate and store one row

array([ 6, 15, 24])

In [61]:
arr.mean()

np.float64(5.0)

In [63]:
arr.argmax()

np.int64(8)

In [64]:
arr.argmin()

np.int64(0)

In [66]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [69]:
arr.reshape(5,6) 

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [70]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])