In [17]:
import numpy as np
d3_array = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)

[ 6  8 10 12]


In [20]:
print(a-b)

[-4 -4 -4 -4]


In [21]:
print(a/b)

[0.2        0.33333333 0.42857143 0.5       ]


In [22]:
print(a*b)

[ 5 12 21 32]


In [23]:
a**2

array([ 1,  4,  9, 16])

In [24]:
a+10

array([11, 12, 13, 14])

In [43]:
a1 = np.array([[1,2,3],[4,5,6]])
b1 = np.array([[7,8,9]])
print(a1.reshape(2,3))
print(a1.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]


In [50]:
num = np.arange(1,10,0.5)
print(num)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [56]:
print(a1.max())
print(a1.min())
print(a1.sum())
print(a1.mean())

6
1
21
3.5


In [58]:
a2 = np.array([[1,2,3],[5,6,7]])
a2.sum(axis=0)
a2.sum(axis=1)

array([ 6, 18])

In [61]:
degrees = np.array([0,np.pi/2,np.pi/4])
print(np.sin(degrees))
print(np.cos(degrees))
print(np.tan(degrees))
print(1/np.sin(degrees))

[0.         1.         0.70710678]
[1.00000000e+00 6.12323400e-17 7.07106781e-01]
[0.00000000e+00 1.63312394e+16 1.00000000e+00]
[       inf 1.         1.41421356]


/var/folders/8q/hf7c_dhj15ggp1zy1l6v8khw0000gn/T/ipykernel_4526/642932021.py:5: RuntimeWarning: divide by zero encountered in divide
  print(1/np.sin(degrees))


In [64]:
random_num = np.random.rand(3)
random_num

array([0.32005158, 0.23947834, 0.47618065])