In [9]:
import numpy as np

In [10]:
arr = np.array([12,21,43,41,55,65,37])
arr1 = np.array([77,76,56,84,43,25,14])
sum_arr = arr + arr1
sum_arr

array([ 89,  97,  99, 125,  98,  90,  51])

In [11]:
sub_arr = arr - arr1
sub_arr

array([-65, -55, -13, -43,  12,  40,  23])

In [12]:
multi_arr = arr * arr1
multi_arr

array([ 924, 1596, 2408, 3444, 2365, 1625,  518])

In [13]:
div_arr = arr / arr1
div_arr

array([0.15584416, 0.27631579, 0.76785714, 0.48809524, 1.27906977,
       2.6       , 2.64285714])

In [14]:
floor_arr = arr // arr1
floor_arr

array([0, 0, 0, 0, 1, 2, 2])

In [15]:
expo_arr = arr ** arr1
expo_arr

array([                   0, -3321159092462303983, -1577905608676222815,
        -127992810615553887, -4502227472361539161,  3902757015977641537,
       -8396556048962440535])

In [17]:
a = [10,22,33,44,55,66]
arr = np.array(a)

In [18]:
arr + 10 # broadcasting

array([20, 32, 43, 54, 65, 76])

In [21]:
arr = np.arange(1,21).reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [24]:
sum_arr1 = arr + 10
sum_arr1

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [25]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
slice = arr[:4]
slice = slice * 10
slice

array([10, 20, 30, 40])